[2024-05-22T01:39:27.959+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T01:39:28.034+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dataset.load manual__2024-05-22T01:16:10.864259+00:00 [queued]>
[2024-05-22T01:39:28.074+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dataset.load manual__2024-05-22T01:16:10.864259+00:00 [queued]>
[2024-05-22T01:39:28.077+0000] {taskinstance.py:2306} INFO - Starting attempt 8 of 12
[2024-05-22T01:39:28.424+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-05-22 01:16:10.864259+00:00
[2024-05-22T01:39:28.440+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1416) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-22T01:39:28.445+0000] {standard_task_runner.py:63} INFO - Started process 1440 to run task
[2024-05-22T01:39:28.442+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dataset', 'load', 'manual__2024-05-22T01:16:10.864259+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dataset.py', '--cfg-path', '/tmp/tmpo6qld140']
[2024-05-22T01:39:28.449+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask load
[2024-05-22T01:39:28.561+0000] {task_command.py:426} INFO - Running <TaskInstance: kaggle_dataset.load manual__2024-05-22T01:16:10.864259+00:00 [running]> on host b17c52120858
[2024-05-22T01:39:28.792+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dataset' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T01:16:10.864259+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-22T01:16:10.864259+00:00'
[2024-05-22T01:39:28.796+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T01:39:28.840+0000] {logging_mixin.py:188} INFO - Hola Mundo
[2024-05-22T01:39:28.841+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-22T01:39:28.843+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T01:39:28.871+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=kaggle_dataset, task_id=load, run_id=manual__2024-05-22T01:16:10.864259+00:00, execution_date=20240522T011610, start_date=20240522T013928, end_date=20240522T013928
[2024-05-22T01:39:28.946+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-22T01:39:29.000+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22T01:39:29.006+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
