[2024-05-22T01:35:41.100+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T01:35:41.173+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dataset.load manual__2024-05-22T01:16:10.864259+00:00 [queued]>
[2024-05-22T01:35:41.209+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dataset.load manual__2024-05-22T01:16:10.864259+00:00 [queued]>
[2024-05-22T01:35:41.212+0000] {taskinstance.py:2306} INFO - Starting attempt 7 of 11
[2024-05-22T01:35:41.575+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-05-22 01:16:10.864259+00:00
[2024-05-22T01:35:41.594+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1253) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-22T01:35:41.600+0000] {standard_task_runner.py:63} INFO - Started process 1277 to run task
[2024-05-22T01:35:41.600+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dataset', 'load', 'manual__2024-05-22T01:16:10.864259+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dataset.py', '--cfg-path', '/tmp/tmp8edb2dt_']
[2024-05-22T01:35:41.606+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask load
[2024-05-22T01:35:41.751+0000] {task_command.py:426} INFO - Running <TaskInstance: kaggle_dataset.load manual__2024-05-22T01:16:10.864259+00:00 [running]> on host b17c52120858
[2024-05-22T01:35:42.033+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dataset' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T01:16:10.864259+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-22T01:16:10.864259+00:00'
[2024-05-22T01:35:42.037+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T01:35:42.085+0000] {logging_mixin.py:188} INFO - Hola Mundo
[2024-05-22T01:35:42.087+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-22T01:35:42.090+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T01:35:42.117+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=kaggle_dataset, task_id=load, run_id=manual__2024-05-22T01:16:10.864259+00:00, execution_date=20240522T011610, start_date=20240522T013541, end_date=20240522T013542
[2024-05-22T01:35:42.182+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-22T01:35:42.235+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22T01:35:42.241+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
