[2024-05-21T22:08:45.410+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T22:08:45.518+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dataset.load manual__2024-05-21T22:05:48.748499+00:00 [queued]>
[2024-05-21T22:08:45.563+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dataset.load manual__2024-05-21T22:05:48.748499+00:00 [queued]>
[2024-05-21T22:08:45.565+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 5
[2024-05-21T22:08:45.945+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-05-21 22:05:48.748499+00:00
[2024-05-21T22:08:45.957+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=246) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T22:08:45.960+0000] {standard_task_runner.py:63} INFO - Started process 270 to run task
[2024-05-21T22:08:45.963+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dataset', 'load', 'manual__2024-05-21T22:05:48.748499+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dataset.py', '--cfg-path', '/tmp/tmpikbvlvnh']
[2024-05-21T22:08:45.969+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask load
[2024-05-21T22:08:46.101+0000] {task_command.py:426} INFO - Running <TaskInstance: kaggle_dataset.load manual__2024-05-21T22:05:48.748499+00:00 [running]> on host 36dd2f748723
[2024-05-21T22:08:46.365+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dataset' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T22:05:48.748499+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T22:05:48.748499+00:00'
[2024-05-21T22:08:46.369+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T22:08:46.420+0000] {logging_mixin.py:188} INFO - Hola Mundo
[2024-05-21T22:08:46.422+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-21T22:08:46.425+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T22:08:46.447+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=kaggle_dataset, task_id=load, run_id=manual__2024-05-21T22:05:48.748499+00:00, execution_date=20240521T220548, start_date=20240521T220845, end_date=20240521T220846
[2024-05-21T22:08:46.500+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-21T22:08:46.538+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T22:08:46.544+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
