[2024-05-23T21:15:48.825+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-23T21:15:48.914+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dataset.extraccion manual__2024-05-23T01:15:45.195685+00:00 [queued]>
[2024-05-23T21:15:48.965+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dataset.extraccion manual__2024-05-23T01:15:45.195685+00:00 [queued]>
[2024-05-23T21:15:48.976+0000] {taskinstance.py:2306} INFO - Starting attempt 17 of 21
[2024-05-23T21:15:49.177+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extraccion> on 2024-05-23 01:15:45.195685+00:00
[2024-05-23T21:15:49.277+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1499) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-23T21:15:49.281+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dataset', 'extraccion', 'manual__2024-05-23T01:15:45.195685+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dataset.py', '--cfg-path', '/tmp/tmp3bejwfds']
[2024-05-23T21:15:49.324+0000] {standard_task_runner.py:63} INFO - Started process 1523 to run task
[2024-05-23T21:15:49.366+0000] {standard_task_runner.py:91} INFO - Job 42: Subtask extraccion
[2024-05-23T21:15:49.575+0000] {task_command.py:426} INFO - Running <TaskInstance: kaggle_dataset.extraccion manual__2024-05-23T01:15:45.195685+00:00 [running]> on host 7ef43f6735eb
[2024-05-23T21:15:49.821+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dataset' AIRFLOW_CTX_TASK_ID='extraccion' AIRFLOW_CTX_EXECUTION_DATE='2024-05-23T01:15:45.195685+00:00' AIRFLOW_CTX_TRY_NUMBER='17' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-23T01:15:45.195685+00:00'
[2024-05-23T21:15:49.825+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-23T21:15:49.903+0000] {logging_mixin.py:188} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/***/.kaggle/kaggle.json'
[2024-05-23T21:15:55.472+0000] {logging_mixin.py:188} INFO - Global Economy Indicators.csv
[2024-05-23T21:15:55.475+0000] {logging_mixin.py:188} INFO - hecho
[2024-05-23T21:15:55.486+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-23T21:15:55.490+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-23T21:15:55.524+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=kaggle_dataset, task_id=extraccion, run_id=manual__2024-05-23T01:15:45.195685+00:00, execution_date=20240523T011545, start_date=20240523T211548, end_date=20240523T211555
[2024-05-23T21:15:55.630+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-23T21:15:55.675+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
