[2024-05-22T01:29:55.315+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T01:29:55.403+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dataset.extraccion manual__2024-05-22T01:16:10.864259+00:00 [queued]>
[2024-05-22T01:29:55.445+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dataset.extraccion manual__2024-05-22T01:16:10.864259+00:00 [queued]>
[2024-05-22T01:29:55.447+0000] {taskinstance.py:2306} INFO - Starting attempt 7 of 11
[2024-05-22T01:29:55.817+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extraccion> on 2024-05-22 01:16:10.864259+00:00
[2024-05-22T01:29:55.835+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=845) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-22T01:29:55.845+0000] {standard_task_runner.py:63} INFO - Started process 869 to run task
[2024-05-22T01:29:55.846+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dataset', 'extraccion', 'manual__2024-05-22T01:16:10.864259+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dataset.py', '--cfg-path', '/tmp/tmpsoc4joqx']
[2024-05-22T01:29:55.852+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask extraccion
[2024-05-22T01:29:56.013+0000] {task_command.py:426} INFO - Running <TaskInstance: kaggle_dataset.extraccion manual__2024-05-22T01:16:10.864259+00:00 [running]> on host b17c52120858
[2024-05-22T01:29:56.309+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dataset' AIRFLOW_CTX_TASK_ID='extraccion' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T01:16:10.864259+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-22T01:16:10.864259+00:00'
[2024-05-22T01:29:56.311+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T01:29:56.361+0000] {logging_mixin.py:188} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/***/.kaggle/kaggle.json'
[2024-05-22T01:30:01.089+0000] {logging_mixin.py:188} INFO - hecho
[2024-05-22T01:30:01.094+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-22T01:30:01.096+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T01:30:01.123+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=kaggle_dataset, task_id=extraccion, run_id=manual__2024-05-22T01:16:10.864259+00:00, execution_date=20240522T011610, start_date=20240522T012955, end_date=20240522T013001
[2024-05-22T01:30:01.189+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-22T01:30:01.270+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22T01:30:01.276+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
