[2024-05-22T01:32:44.164+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T01:32:44.224+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dataset.extraccion manual__2024-05-22T01:16:10.864259+00:00 [queued]>
[2024-05-22T01:32:44.255+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dataset.extraccion manual__2024-05-22T01:16:10.864259+00:00 [queued]>
[2024-05-22T01:32:44.257+0000] {taskinstance.py:2306} INFO - Starting attempt 8 of 12
[2024-05-22T01:32:44.632+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extraccion> on 2024-05-22 01:16:10.864259+00:00
[2024-05-22T01:32:44.654+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1001) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-22T01:32:44.659+0000] {standard_task_runner.py:63} INFO - Started process 1025 to run task
[2024-05-22T01:32:44.661+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dataset', 'extraccion', 'manual__2024-05-22T01:16:10.864259+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dataset.py', '--cfg-path', '/tmp/tmpwk1p8myz']
[2024-05-22T01:32:44.668+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask extraccion
[2024-05-22T01:32:44.840+0000] {task_command.py:426} INFO - Running <TaskInstance: kaggle_dataset.extraccion manual__2024-05-22T01:16:10.864259+00:00 [running]> on host b17c52120858
[2024-05-22T01:32:45.080+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dataset' AIRFLOW_CTX_TASK_ID='extraccion' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T01:16:10.864259+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-22T01:16:10.864259+00:00'
[2024-05-22T01:32:45.085+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T01:32:45.141+0000] {logging_mixin.py:188} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/***/.kaggle/kaggle.json'
[2024-05-22T01:32:49.166+0000] {logging_mixin.py:188} INFO - Global Economy Indicators.csv
[2024-05-22T01:32:49.168+0000] {logging_mixin.py:188} INFO - hecho
[2024-05-22T01:32:49.176+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-22T01:32:49.179+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T01:32:49.212+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=kaggle_dataset, task_id=extraccion, run_id=manual__2024-05-22T01:16:10.864259+00:00, execution_date=20240522T011610, start_date=20240522T013244, end_date=20240522T013249
[2024-05-22T01:32:49.310+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-22T01:32:49.397+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22T01:32:49.403+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
