[2024-05-22T01:39:14.716+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T01:39:14.795+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dataset.extraccion manual__2024-05-22T01:16:10.864259+00:00 [queued]>
[2024-05-22T01:39:14.832+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dataset.extraccion manual__2024-05-22T01:16:10.864259+00:00 [queued]>
[2024-05-22T01:39:14.835+0000] {taskinstance.py:2306} INFO - Starting attempt 10 of 14
[2024-05-22T01:39:15.128+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extraccion> on 2024-05-22 01:16:10.864259+00:00
[2024-05-22T01:39:15.145+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1313) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-22T01:39:15.149+0000] {standard_task_runner.py:63} INFO - Started process 1337 to run task
[2024-05-22T01:39:15.150+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dataset', 'extraccion', 'manual__2024-05-22T01:16:10.864259+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dataset.py', '--cfg-path', '/tmp/tmpmfj1juko']
[2024-05-22T01:39:15.156+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask extraccion
[2024-05-22T01:39:15.288+0000] {task_command.py:426} INFO - Running <TaskInstance: kaggle_dataset.extraccion manual__2024-05-22T01:16:10.864259+00:00 [running]> on host b17c52120858
[2024-05-22T01:39:15.510+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dataset' AIRFLOW_CTX_TASK_ID='extraccion' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T01:16:10.864259+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-22T01:16:10.864259+00:00'
[2024-05-22T01:39:15.513+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T01:39:15.591+0000] {logging_mixin.py:188} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/***/.kaggle/kaggle.json'
[2024-05-22T01:39:20.533+0000] {logging_mixin.py:188} INFO - Global Economy Indicators.csv
[2024-05-22T01:39:20.534+0000] {logging_mixin.py:188} INFO - hecho
[2024-05-22T01:39:20.542+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-22T01:39:20.544+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T01:39:20.565+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=kaggle_dataset, task_id=extraccion, run_id=manual__2024-05-22T01:16:10.864259+00:00, execution_date=20240522T011610, start_date=20240522T013914, end_date=20240522T013920
[2024-05-22T01:39:20.653+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-22T01:39:20.743+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22T01:39:20.748+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
